/**
 * A curated emoji list, not the full ~3,800-codepoint Unicode set, and not an
 * emoji-picker dependency: a few hundred hand-picked characters cover what
 * anyone actually reacts with, ship as one small string, and stay scannable.
 *
 * Format is "char keyword keyword" joined by "|" purely to keep the source
 * compact — it is parsed once, at module load.
 */
const RAW = {
  Smileys:
    "😀 grin happy|😃 smile happy|😄 laugh happy|😁 beam grin|😆 laugh lol|😅 sweat laugh|🤣 rofl laugh|😂 joy tears laugh|🙂 slight smile|🙃 upside down|😉 wink|😊 blush smile|😇 halo angel|🥰 love hearts|😍 heart eyes love|🤩 star struck wow|😘 kiss|😗 kiss|😚 kiss|😙 kiss|🥲 tear smile|😋 yum tasty|😛 tongue|😜 wink tongue|🤪 zany crazy|😝 tongue squint|🤑 money|🤗 hug|🤭 giggle oops|🤫 shush quiet|🤔 think hmm|🤐 zipper quiet|🤨 raised eyebrow|😐 neutral|😑 expressionless|😶 no mouth|😏 smirk|😒 unamused meh|🙄 eye roll|😬 grimace awkward|🤥 lying|😌 relieved calm|😔 pensive sad|😪 sleepy|🤤 drool|😴 sleep zzz|😷 mask sick|🤒 sick fever|🤕 hurt injured|🤢 nauseated sick|🤮 vomit sick|🤧 sneeze|🥵 hot|🥶 cold freezing|🥴 woozy|😵 dizzy|🤯 mind blown|🤠 cowboy|🥳 party celebrate|😎 cool sunglasses|🤓 nerd geek|🧐 monocle|😕 confused|😟 worried|🙁 frown sad|😮 open mouth wow|😯 hushed|😲 astonished shock|😳 flushed|🥺 pleading please|😦 frown|😧 anguished|😨 fearful|😰 anxious|😥 sad|😢 cry sad|😭 sob cry|😱 scream shock|😖 confounded|😣 persevere|😞 disappointed|😓 downcast sweat|😩 weary tired|😫 tired|🥱 yawn bored|😤 triumph huff|😡 rage angry|😠 angry mad|🤬 cursing swear|😈 devil smiling|👿 imp angry|💀 skull dead|💩 poop|🤡 clown|👻 ghost|👽 alien|🤖 robot|😺 cat grin|😹 cat joy|😻 cat love|🙀 cat shock|😿 cat cry",
  Gestures:
    "👍 thumbs up yes like|👎 thumbs down no dislike|👌 ok perfect|🤌 pinched italian|🤏 pinch small|✌️ victory peace|🤞 crossed fingers luck|🤟 love you|🤘 rock horns|🤙 call me shaka|👈 point left|👉 point right|👆 point up|👇 point down|☝️ point up|✋ raised hand stop|🤚 back hand|🖐️ hand fingers|🖖 vulcan spock|👋 wave hello bye|🤝 handshake deal|👏 clap applause bravo|🙌 raise hands praise|👐 open hands|🤲 palms up|🙏 pray thanks please|✍️ writing|💪 muscle strong|🦾 mechanical arm|🖕 middle finger|✊ fist|👊 punch fist bump|🤛 left fist|🤜 right fist|🫶 heart hands love|🫡 salute|🫠 melting",
  People:
    "👶 baby|🧒 child|👦 boy|👧 girl|🧑 person|👨 man|👩 woman|🧓 older person|👴 old man|👵 old woman|🧔 beard|👮 police|🕵️ detective spy|💂 guard|👷 construction worker|🤴 prince|👸 princess|👳 turban|🧑‍⚕️ health worker doctor|🧑‍🎓 student graduate|🧑‍🏫 teacher|🧑‍🌾 farmer|🧑‍🍳 cook chef|🧑‍🔧 mechanic|🧑‍🏭 factory worker|🧑‍💼 office worker|🧑‍🔬 scientist|🧑‍💻 technologist developer|🧑‍🎤 singer|🧑‍🎨 artist|🧑‍✈️ pilot|🧑‍🚀 astronaut|🧑‍🚒 firefighter|🎅 santa|🦸 superhero|🦹 supervillain|🧙 mage wizard|🧚 fairy|🧛 vampire|🧜 merperson|🧝 elf|🙅 no gesture|🙆 ok gesture|💁 tipping hand sassy|🙋 raising hand|🧏 deaf|🙇 bow sorry|🤦 facepalm|🤷 shrug|💃 dancer|🕺 dancing man|🕴️ suit levitate|👯 bunny ears party|🧖 sauna spa|🧗 climbing|🤺 fencing|🏇 horse racing|⛷️ ski|🏂 snowboard|🏌️ golf|🏄 surf|🚣 row boat|🏊 swim|⛹️ basketball|🏋️ weight lift|🚴 bike cycling|🚵 mountain bike|🤸 cartwheel|🤼 wrestle|🤽 water polo|🤾 handball|🤹 juggle|🧘 yoga meditate|🛀 bath|🛌 sleep bed|👭 two women|👫 couple|👬 two men|💏 kiss couple|💑 couple heart|👪 family|👨‍👩‍👧‍👦 family kids|🗣️ speaking|👤 silhouette|👣 footprints",
  Nature:
    "🐶 dog puppy|🐱 cat kitten|🐭 mouse|🐹 hamster|🐰 rabbit bunny|🦊 fox|🐻 bear|🐼 panda|🐨 koala|🐯 tiger|🦁 lion|🐮 cow|🐷 pig|🐸 frog|🐵 monkey|🙈 see no evil|🙉 hear no evil|🙊 speak no evil|🐒 monkey|🐔 chicken|🐧 penguin|🐦 bird|🐤 chick|🦆 duck|🦅 eagle|🦉 owl|🦇 bat|🐺 wolf|🐗 boar|🐴 horse|🦄 unicorn|🐝 bee|🐛 bug caterpillar|🦋 butterfly|🐌 snail|🐞 ladybug|🐜 ant|🦗 cricket|🕷️ spider|🦂 scorpion|🐢 turtle|🐍 snake|🦎 lizard|🦖 t-rex dinosaur|🐙 octopus|🦑 squid|🦐 shrimp|🦀 crab|🐡 blowfish|🐠 fish tropical|🐟 fish|🐬 dolphin|🐳 whale|🦈 shark|🐊 crocodile|🐅 tiger|🦓 zebra|🦍 gorilla|🐘 elephant|🦏 rhino|🐪 camel|🦒 giraffe|🐃 buffalo|🐎 horse|🐖 pig|🐑 sheep|🐐 goat|🦌 deer|🐕 dog|🐈 cat|🐓 rooster|🦃 turkey|🕊️ dove peace|🐇 rabbit|🐁 mouse|🐿️ chipmunk|🦔 hedgehog|🐾 paw prints|🌵 cactus|🎄 christmas tree|🌲 evergreen|🌳 tree|🌴 palm tree|🌱 seedling|🌿 herb|☘️ shamrock|🍀 four leaf clover luck|🎋 bamboo|🍃 leaves wind|🍂 fallen leaves autumn|🍁 maple leaf|🍄 mushroom|🐚 shell|🌾 rice sheaf|💐 bouquet flowers|🌷 tulip|🌹 rose|🥀 wilted flower|🌺 hibiscus|🌸 cherry blossom|🌼 blossom|🌻 sunflower|🌞 sun face|🌝 full moon face|🌛 moon face|🌜 moon face|🌚 new moon face|🌕 full moon|🌙 crescent moon|🌍 earth globe|🌎 earth americas|🌏 earth asia|💫 dizzy stars|⭐ star|🌟 glowing star|✨ sparkles|⚡ zap lightning|☄️ comet|💥 boom collision|🔥 fire lit|🌪️ tornado|🌈 rainbow|☀️ sun|🌤️ sun cloud|⛅ partly cloudy|☁️ cloud|🌧️ rain|⛈️ thunderstorm|🌩️ lightning|🌨️ snow cloud|❄️ snowflake|☃️ snowman|⛄ snowman|🌬️ wind|💨 dash wind|💧 droplet|💦 sweat drops|☔ umbrella rain|🌊 wave ocean",
  Food:
    "🍏 green apple|🍎 apple|🍐 pear|🍊 orange tangerine|🍋 lemon|🍌 banana|🍉 watermelon|🍇 grapes|🍓 strawberry|🫐 blueberries|🍈 melon|🍒 cherries|🍑 peach|🥭 mango|🍍 pineapple|🥥 coconut|🥝 kiwi|🍅 tomato|🍆 eggplant|🥑 avocado|🥦 broccoli|🥬 leafy green|🥒 cucumber|🌶️ hot pepper spicy|🌽 corn|🥕 carrot|🧄 garlic|🧅 onion|🥔 potato|🍠 sweet potato|🥐 croissant|🥯 bagel|🍞 bread|🥖 baguette|🧀 cheese|🥚 egg|🍳 cooking egg|🧈 butter|🥞 pancakes|🧇 waffle|🥓 bacon|🍔 burger|🍟 fries|🌭 hot dog|🍕 pizza|🥪 sandwich|🌮 taco|🌯 burrito|🥗 salad|🥘 pan food|🍝 spaghetti pasta|🍜 ramen noodles|🍲 stew|🍛 curry|🍣 sushi|🍱 bento|🥟 dumpling|🍤 fried shrimp|🍚 rice|🍘 rice cracker|🍥 fish cake|🥠 fortune cookie|🍢 oden|🍡 dango|🍧 shaved ice|🍨 ice cream|🍦 soft serve|🥧 pie|🧁 cupcake|🍰 cake|🎂 birthday cake|🍮 custard|🍭 lollipop|🍬 candy|🍫 chocolate|🍿 popcorn|🍩 doughnut|🍪 cookie|🥛 milk|🍼 baby bottle|☕ coffee tea|🍵 tea|🧃 juice box|🥤 cup straw soda|🧋 bubble tea|🍶 sake|🍺 beer|🍻 cheers beers|🥂 clink glasses toast|🍷 wine|🥃 whisky|🍸 cocktail|🍹 tropical drink|🧉 mate|🍾 champagne bottle|🧊 ice|🥄 spoon|🍴 fork knife|🍽️ plate|🧂 salt",
  Activity:
    "⚽ soccer football|🏀 basketball|🏈 football|⚾ baseball|🥎 softball|🎾 tennis|🏐 volleyball|🏉 rugby|🥏 frisbee|🎳 bowling|🏏 cricket|🏑 field hockey|🏒 hockey|🥍 lacrosse|🏓 ping pong|🏸 badminton|🥊 boxing|🥋 martial arts|🥅 goal|⛳ golf|🎣 fishing|🤿 diving|🎽 running shirt|🎿 skis|🛷 sled|🥌 curling|🎯 target bullseye|🪀 yo-yo|🪁 kite|🎱 8 ball pool|🔮 crystal ball|🧿 evil eye|🎮 video game|🕹️ joystick|🎰 slot machine|🎲 dice|🧩 puzzle|🧸 teddy bear|🎨 art palette|🎬 clapper film|🎤 microphone|🎧 headphones|🎼 music score|🎹 piano|🥁 drum|🎷 saxophone|🎺 trumpet|🎸 guitar|🪕 banjo|🎻 violin|🏆 trophy win|🥇 gold medal first|🥈 silver medal|🥉 bronze medal|🏅 medal|🎖️ military medal|🎗️ ribbon|🎫 ticket|🎟️ admission ticket|🎪 circus|🤹 juggling|🎭 theatre masks|🎉 party popper celebrate|🎊 confetti|🎈 balloon|🎁 gift present|🎀 ribbon bow|🎇 sparkler|🎆 fireworks|🧨 firecracker",
  Travel:
    "🚗 car|🚕 taxi|🚙 suv|🚌 bus|🚎 trolleybus|🏎️ race car|🚓 police car|🚑 ambulance|🚒 fire engine|🚐 minibus|🚚 truck|🚛 lorry|🚜 tractor|🛴 scooter|🚲 bicycle bike|🛵 motor scooter|🏍️ motorcycle|🚨 siren light|🚔 police|🚍 bus|🚘 car|🚖 taxi|🚡 aerial tramway|🚠 gondola|🚟 suspension railway|🚃 railway car|🚋 tram|🚞 mountain railway|🚝 monorail|🚄 bullet train|🚅 shinkansen|🚈 light rail|🚂 locomotive train|🚆 train|🚇 metro subway|🚊 tram|🚉 station|✈️ airplane flight|🛫 departure takeoff|🛬 arrival landing|🛩️ small plane|💺 seat|🚁 helicopter|🚀 rocket launch|🛸 ufo|🛶 canoe|⛵ sailboat|🚤 speedboat|🛥️ motor boat|🛳️ passenger ship|⛴️ ferry|🚢 ship|⚓ anchor|🚧 construction|⛽ fuel gas|🚏 bus stop|🗺️ map|🗿 moai statue|🗽 statue of liberty|🗼 tokyo tower|🏰 castle|🏯 japanese castle|🏟️ stadium|🎡 ferris wheel|🎢 roller coaster|🎠 carousel|⛲ fountain|⛱️ beach umbrella|🏖️ beach|🏝️ desert island|🏜️ desert|🌋 volcano|⛰️ mountain|🏔️ snowy mountain|🗻 mount fuji|🏕️ camping|⛺ tent|🏠 house home|🏡 house garden|🏘️ houses|🏢 office building|🏥 hospital|🏦 bank|🏨 hotel|🏫 school|🏭 factory|🏬 department store|🏛️ classical building|⛪ church|🕌 mosque|🛕 hindu temple|🕍 synagogue|🌃 night city|🌆 cityscape dusk|🌇 sunset|🌉 bridge night|🌌 milky way|🎑 moon ceremony|🏙️ cityscape",
  Objects:
    "⌚ watch|📱 phone mobile|💻 laptop computer|⌨️ keyboard|🖥️ desktop|🖨️ printer|🖱️ mouse|💽 disk|💾 floppy save|💿 cd|📀 dvd|📷 camera|📸 camera flash|📹 video camera|🎥 movie camera|📽️ projector|📺 tv|📻 radio|🎙️ studio mic|⏰ alarm clock|⏱️ stopwatch|⌛ hourglass|🔋 battery|🔌 plug|💡 bulb idea|🔦 flashlight|🕯️ candle|🪔 diya lamp|🧯 extinguisher|🛢️ oil drum|💸 money wings|💵 dollar|💴 yen|💶 euro|💷 pound|💰 money bag|💳 credit card|💎 gem diamond|⚖️ scales justice|🔧 wrench|🔨 hammer|⚒️ tools|🛠️ hammer wrench|⛏️ pick|🔩 bolt nut|⚙️ gear settings|🧱 brick|⛓️ chains|🧲 magnet|🔫 water pistol|💣 bomb|🧨 dynamite|🪓 axe|🔪 knife|🗡️ dagger|🛡️ shield|🚬 cigarette|⚰️ coffin|🏺 amphora|🔭 telescope|🔬 microscope|🕳️ hole|💊 pill|💉 syringe|🩸 blood|🩹 bandage|🩺 stethoscope|🌡️ thermometer|🧬 dna|🦠 microbe virus|🧪 test tube|🧫 petri dish|🧹 broom|🧺 basket|🧻 toilet paper|🚽 toilet|🚿 shower|🛁 bathtub|🧼 soap|🪥 toothbrush|🔑 key|🗝️ old key|🚪 door|🪑 chair|🛋️ couch|🛏️ bed|🧳 luggage|🛒 shopping cart|🎁 gift|🎈 balloon|📩 envelope|📧 email|📨 incoming mail|📤 outbox|📥 inbox|📦 package box|📪 mailbox|📫 mailbox|📮 postbox|✉️ envelope|📝 memo note|✏️ pencil|✒️ pen|🖊️ pen|🖍️ crayon|🖌️ paintbrush|📏 ruler|📐 triangle ruler|📌 pushpin|📍 round pin location|📎 paperclip|🖇️ paperclips|✂️ scissors|🗃️ card box|🗄️ file cabinet|🗑️ wastebasket trash|🔒 lock|🔓 unlock|🔏 lock pen|🔐 lock key|📔 notebook|📕 closed book|📖 open book|📗 green book|📘 blue book|📙 orange book|📚 books|📓 notebook|📒 ledger|📃 page|📜 scroll|📄 page|📰 newspaper|🗞️ rolled newspaper|📑 bookmark tabs|🔖 bookmark|🏷️ label tag|📊 bar chart|📈 chart up|📉 chart down|🗒️ notepad|🗓️ calendar|📆 calendar|📅 date|🗑️ trash|📁 folder|📂 open folder|🗂️ dividers|📋 clipboard|🖇️ clip|🔍 magnify search|🔎 magnify|🔨 hammer|🧰 toolbox|🪄 magic wand|🎓 graduation cap|👑 crown|💍 ring|👗 dress|👕 shirt|👖 jeans|👟 shoe sneaker|👠 heels|🎒 backpack|🕶️ sunglasses|👓 glasses|🧢 cap|🎩 top hat|⛑️ rescue helmet|☂️ umbrella",
  Symbols:
    "❤️ red heart love|🧡 orange heart|💛 yellow heart|💚 green heart|💙 blue heart|💜 purple heart|🖤 black heart|🤍 white heart|🤎 brown heart|💔 broken heart|❣️ heart exclamation|💕 two hearts|💞 revolving hearts|💓 beating heart|💗 growing heart|💖 sparkling heart|💘 heart arrow cupid|💝 heart ribbon gift|💟 heart decoration|❤️‍🔥 heart on fire|❤️‍🩹 mending heart|💯 hundred perfect|💢 anger|💬 speech bubble|👁️‍🗨️ eye speech|🗨️ left speech|🗯️ anger bubble|💭 thought bubble|💤 zzz sleep|☮️ peace|✝️ cross|☪️ star crescent|🕉️ om|☸️ dharma wheel|✡️ star of david|🔯 six pointed star|🕎 menorah|☯️ yin yang|☦️ orthodox cross|🛐 place of worship|⛎ ophiuchus|♈ aries|♉ taurus|♊ gemini|♋ cancer|♌ leo|♍ virgo|♎ libra|♏ scorpio|♐ sagittarius|♑ capricorn|♒ aquarius|♓ pisces|🆔 id|⚛️ atom|🉑 accept|☢️ radioactive|☣️ biohazard|📴 phone off|📳 vibration|🈶 not free|🈚 free|🈸 application|🈺 open for business|🈷️ monthly amount|✴️ eight pointed star|🆚 versus vs|💮 white flower|🉐 bargain|㊙️ secret|㊗️ congratulations|🈴 pass|🈵 no vacancy|🈹 discount|🈲 prohibited|🅰️ a button|🅱️ b button|🆎 ab button|🆑 cl button|🅾️ o button|🆘 sos help|❌ cross mark no|⭕ hollow circle|🛑 stop sign|⛔ no entry|📛 name badge|🚫 prohibited no|💯 hundred|💠 diamond dot|♻️ recycle|⚜️ fleur de lis|🔱 trident|📵 no phones|🔞 no under 18|📢 loudspeaker announce|📣 megaphone cheer|🔔 bell notification|🔕 bell off mute|🎵 music note|🎶 music notes|➕ plus|➖ minus|➗ divide|✖️ multiply|♾️ infinity|‼️ double exclamation|⁉️ exclamation question|❓ question|❔ white question|❕ white exclamation|❗ exclamation|〰️ wavy dash|⚠️ warning|🚸 children crossing|🔰 beginner|✅ check mark done|☑️ ballot check|✔️ check|🔟 keycap ten|🔠 uppercase|🔡 lowercase|🔢 numbers|🔣 symbols|🔤 letters abc|🅿️ parking|🚾 wc|♿ wheelchair accessible|🛗 elevator|🈳 vacancy|🈂️ service charge|🛂 passport control|🛃 customs|🛄 baggage claim|🛅 left luggage|🔄 refresh loop|🔃 clockwise|🔙 back|🔚 end|🔛 on|🔜 soon|🔝 top|⬆️ up|⬇️ down|⬅️ left|➡️ right|↗️ up right|↘️ down right|↙️ down left|↖️ up left|↕️ up down|↔️ left right|↩️ right hook reply|↪️ left hook|⤴️ curve up|⤵️ curve down|🔀 shuffle|🔁 repeat|🔂 repeat one|▶️ play|⏸️ pause|⏹️ stop|⏺️ record|⏭️ next track|⏮️ previous track|⏩ fast forward|⏪ rewind|🔼 up small|🔽 down small|⏫ double up|⏬ double down|🔅 dim|🔆 bright|⚪ white circle|⚫ black circle|🔴 red circle|🔵 blue circle|🟠 orange circle|🟡 yellow circle|🟢 green circle|🟣 purple circle|🟤 brown circle|🔶 orange diamond|🔷 blue diamond|🔸 small orange diamond|🔹 small blue diamond|🔺 red triangle up|🔻 red triangle down|🔲 black square button|🔳 white square button|⬛ black square|⬜ white square|🟥 red square|🟧 orange square|🟨 yellow square|🟩 green square|🟦 blue square|🟪 purple square|🟫 brown square|🃏 joker|🀄 mahjong|🎴 flower cards|♠️ spades|♥️ hearts|♦️ diamonds|♣️ clubs|♟️ chess pawn",
};

/** [{ name, emojis: [{ char, keywords }] }] — the picker's whole data model. */
export const EMOJI_GROUPS = Object.entries(RAW).map(([name, list]) => ({
  name,
  emojis: list.split("|").map((entry) => {
    const space = entry.indexOf(" ");
    return { char: entry.slice(0, space), keywords: entry.slice(space + 1) };
  }),
}));

/** Substring match on the keywords, in group order. Empty term = no filter. */
export function searchEmoji(term) {
  const needle = term.trim().toLowerCase();
  if (!needle) return EMOJI_GROUPS;

  return EMOJI_GROUPS.map((group) => ({
    ...group,
    emojis: group.emojis.filter(({ keywords }) => keywords.includes(needle)),
  })).filter((group) => group.emojis.length);
}